### PR TITLE
Support more hw and refactor

### PR DESCRIPTION
**Pull request by erikthi**
Brings in changes from a non public repo with the following benefits:

- Add support for nrf52832dk board.
- Add support for dps310
- Add support for lis2dh12
- Add support for shtc3
- Update udp_to_influx.py to use python3
- Refactored folder structure to be more modular
- Removed unused code e.g repeater example
- Update documentation

### CODE REVIEW

**Comment by pengi** [comment]
Nice!

Two thinigs, first Makefile:

`make` is always intended to be ran from the root directory, and no recursive makes with `make -C ...` is used. Thus, `$(CURDIR)` just make long paths and command lines. I suggest just using relative paths everywhere instead. Think that would be cleaner.

For example here: https://github.com/LumenRadio/mira-ruuvitag/pull/3/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R18-R19

We're not going to move around the source that much. If so, then search/replace in Makefile would make it cleaner I think rather than using the variables here. But that's just a matter of taste... Think it makes searching for references easier too.

https://github.com/LumenRadio/mira-ruuvitag/pull/3/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R41-R44


Next thing is the `udp_to_influx.py`:

https://github.com/LumenRadio/mira-ruuvitag/pull/3/files#diff-99115573426114db00d4b2b1905e685ff4f397623efe1e0760803d7b7f7d4b4cR10

Think `root_addr` shouldn't be in the script, more than a commented out example.

Best is to auto-detect it, but don't think that's possible now.

Second best is to take it as command line argument.

Then next option is to comment out the line, but add a test if it is defined, and if so print out an error message with instructions how to fix it.

If having it defined here, I think most won't notice it and just not get the correct behaviour

**Comment by pengi** [comment]
Also, `src/.DS_Store` should probably not be in the repo

**Comment by erikthi** [comment]
> Also, `src/.DS_Store` should probably not be in the repo
Fixed.

**Review by pengi — APPROVED** [review]
Think it's fine, so the rest of the comments is up to you if you want to include :) nice done

**Pull request merged**
