### PR TITLE
Fix uninitialized sensor bug

### PR DESCRIPTION
**Pull request by erikthi**
Fix a bug with uninitialized sensors causing no sequence number to be sent
Send sequence number as part of the header
Some minor refactoring to udp to influx

### CODE REVIEW

**Review by pengi — APPROVED** [review]
Agree that it makes sense to have the sequence number there. Nice!

I'm thinking however, it breaks compatibility with existing ruuvitags running. However, looking at the seq_nr, it might even have been broken compatibility between the internal and github version before syncing.

Was looking at the protocol... looks like it needs some more overhaul though, but for another time probably :P (sending IP addresses as 16 binary bytes is more efficient. But converting the sensor list to a proper TLV for example)

**Comment by erikthi** [comment]
> Agree that it makes sense to have the sequence number there. Nice!
> 
> I'm thinking however, it breaks compatibility with existing ruuvitags running. However, looking at the seq_nr, it might even have been broken compatibility between the internal and github version before syncing.
> 
> Was looking at the protocol... looks like it needs some more overhaul though, but for another time probably :P (sending IP addresses as 16 binary bytes is more efficient. But converting the sensor list to a proper TLV for example)

Agreed. I don't bother too much with compatibility for now. I think we need to get the project in decent shape before that.

**Comment by SathiyalingamSenthilkumar** [comment]
I was looking into this PR didn't notice that it was merged. I like the idea of having the seq number in the header.

After you are done with all the changes it would be good to format the code.

**Comment by erikthi** [comment]
> I was looking into this PR didn't notice that it was merged. I like the idea of having the seq number in the header.
> 
> After you are done with all the changes it would be good to format the code.

Good idea. Would be nice to use GitHub actions to run formatting and unit tests. I will look into it.

**Pull request merged**
